spring:
  application:
    name: client-service
server:
  port: ${PORT:8081}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
management:
  endpoint:
    shutdown:
      enabled: true
      sensitive: false
