spring:
  profiles: zone1
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
server:
  port: ${PORT:8081}
---
spring:
  profiles: zone2
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
server:
  port: ${PORT:8082}
---
spring:
  profiles: zone3
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
server:
  port: ${PORT:8083}
#spring:
#  application:
#    name: client-service
#server:
#  port: ${PORT:8081}
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: client
#eureka:
#  instance:
#    non-secure-port-enabled: true
#    secure-port-enabled: true
#    status-page-url: https://${eureka.hostname}:${server.port}/info
#    health-check-url: https://${eureka.hostname}:${server.port}/health
#    home-page-url: https://${eureka.hostname}:${server.port}/
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
#management:
#  endpoint:
#    shutdown:
#      enabled: true
#      sensitive: false

