spring:
  application:
    name: client-service
server:
port: 808${SEQUENCE_NO}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 3
    disable-delta: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    instance-id: ${spring.application.name}-${SEQUENCE_NO}
management:
  endpoint:
    shutdown:
      enabled: true